Task 6 -  Coding Questions
These questions are designed to deepen your understanding of system analysis and design and the programming concepts within the context of the proposed university administration system. 
1.	Create your ERD using the programming language of our choice (e.g., SQL Workbench, Apex, MySQL). These questions can also be addressed using Python.

Display all students who received a grade greater than 70% from an enrolment date of your choice, using the enrolment, student, and grades tables in your database schema.

2.	Display the timetable of a single apprentice, displaying the upcoming work and academic commitments between 2 dates

3.	Calculate the average grade for all apprentices for each course and then calculate the average grade by company.

4.	List all apprentices who have completed their apprenticeship program within the last six months, including details such as their final grades and company feedback.

In [9]:
# Schema for the tables used in the examples
# Student Table
students = [
    {"student_id": 1, "student_name": "John Smith", "student_email": "john.smith@example.com", "student_address": "123 Main St, London"},
    {"student_id": 2, "student_name": "Emily Johnson", "student_email": "emily.johnson@example.com", "student_address": "456 Elm St, London"},
    {"student_id": 3, "student_name": "Michael Brown", "student_email": "michael.brown@example.com", "student_address": "789 Oak St, London"},
    {"student_id": 4, "student_name": "Emma Davis", "student_email": "emma.davis@example.com", "student_address": "321 Maple St, London"},
    {"student_id": 5, "student_name": "Daniel Wilson", "student_email": "daniel.wilson@example.com", "student_address": "654 Pine St, London"},
    {"student_id": 6, "student_name": "Sophia Lee", "student_email": "sophia.lee@example.com", "student_address": "987 Cedar St, London"},
    {"student_id": 7, "student_name": "James Taylor", "student_email": "james.taylor@example.com", "student_address": "234 Birch St, London"},
    {"student_id": 8, "student_name": "Olivia Clark", "student_email": "olivia.clark@example.com", "student_address": "567 Walnut St, London"},
    {"student_id": 9, "student_name": "Alexander Martinez", "student_email": "alexander.martinez@example.com", "student_address": "890 Chestnut St, London"},
    {"student_id": 10, "student_name": "Isabella Robinson", "student_email": "isabella.robinson@example.com", "student_address": "432 Spruce St, London"}
]

# Enrolment Table
enrolments = [
    {"enrolment_id": 1, "student_id": 1, "course_id": 101, "enrolment_date": "2023-01-15"},
    {"enrolment_id": 2, "student_id": 2, "course_id": 102, "enrolment_date": "2023-02-20"},
    {"enrolment_id": 3, "student_id": 3, "course_id": 103, "enrolment_date": "2023-03-10"},
    {"enrolment_id": 4, "student_id": 4, "course_id": 101, "enrolment_date": "2023-01-15"},
    {"enrolment_id": 5, "student_id": 5, "course_id": 102, "enrolment_date": "2023-02-20"},
    {"enrolment_id": 6, "student_id": 6, "course_id": 103, "enrolment_date": "2023-03-10"},
    {"enrolment_id": 7, "student_id": 7, "course_id": 101, "enrolment_date": "2023-01-15"},
    {"enrolment_id": 8, "student_id": 8, "course_id": 102, "enrolment_date": "2023-02-20"},
    {"enrolment_id": 9, "student_id": 9, "course_id": 103, "enrolment_date": "2023-03-10"},
    {"enrolment_id": 10, "student_id": 10, "course_id": 101, "enrolment_date": "2023-01-15"}
]

# Grades Table
grades = [
    {"grade_id": 1, "enrolment_id": 1, "grade": 85},
    {"grade_id": 2, "enrolment_id": 2, "grade": 78},
    {"grade_id": 3, "enrolment_id": 3, "grade": 92},
    {"grade_id": 4, "enrolment_id": 4, "grade": 80},
    {"grade_id": 5, "enrolment_id": 5, "grade": 87},
    {"grade_id": 6, "enrolment_id": 6, "grade": 75},
    {"grade_id": 7, "enrolment_id": 7, "grade": 82},
    {"grade_id": 8, "enrolment_id": 8, "grade": 79},
    {"grade_id": 9, "enrolment_id": 9, "grade": 88},
    {"grade_id": 10, "enrolment_id": 10, "grade": 83}
]

# Apprentice Table
apprentices = [
    {"apprentice_id": 1, "apprentice_name": "Mark Thompson", "company_id": 201, "enrolment_date": "2023-01-10", "completion_date": "2023-07-10", "final_grade": 82},
    {"apprentice_id": 2, "apprentice_name": "Sarah White", "company_id": 202, "enrolment_date": "2023-02-15", "completion_date": "2023-08-15", "final_grade": 88},
    {"apprentice_id": 3, "apprentice_name": "Ryan Harris", "company_id": 203, "enrolment_date": "2023-03-20", "completion_date": "2023-09-20", "final_grade": 79},
    {"apprentice_id": 4, "apprentice_name": "Jessica Hall", "company_id": 201, "enrolment_date": "2023-01-10", "completion_date": "2023-07-10", "final_grade": 85},
    {"apprentice_id": 5, "apprentice_name": "David Young", "company_id": 202, "enrolment_date": "2023-02-15", "completion_date": "2023-08-15", "final_grade": 90},
    {"apprentice_id": 6, "apprentice_name": "Amy King", "company_id": 203, "enrolment_date": "2023-03-20", "completion_date": "2023-09-20", "final_grade": 76},
    {"apprentice_id": 7, "apprentice_name": "Luke Scott", "company_id": 201, "enrolment_date": "2023-01-10", "completion_date": "2023-07-10", "final_grade": 84},
    {"apprentice_id": 8, "apprentice_name": "Julia Baker", "company_id": 202, "enrolment_date": "2023-02-15", "completion_date": "2023-08-15", "final_grade": 86},
    {"apprentice_id": 9, "apprentice_name": "Andrew Green", "company_id": 203, "enrolment_date": "2023-03-20", "completion_date": "2023-09-20", "final_grade": 81},
    {"apprentice_id": 10, "apprentice_name": "Sophie Adams", "company_id": 201, "enrolment_date": "2023-01-10", "completion_date": "2023-07-10", "final_grade": 89}
]

# Feedback Table
feedback = [
    {"apprentice_id": 1, "company_feedback": "Mark performed exceptionally well throughout the apprenticeship period."},
    {"apprentice_id": 2, "company_feedback": "Sarah showed great dedication and improvement in her skills."},
    {"apprentice_id": 3, "company_feedback": "Ryan struggled initially but showed steady progress over time."},
    {"apprentice_id": 4, "company_feedback": "Jessica consistently met expectations and contributed positively."},
    {"apprentice_id": 5, "company_feedback": "David exceeded expectations with high-quality work and commitment."},
    {"apprentice_id": 6, "company_feedback": "Amy needed more support initially but showed improvement."},
    {"apprentice_id": 7, "company_feedback": "Luke demonstrated strong analytical skills and problem-solving abilities."},
    {"apprentice_id": 8, "company_feedback": "Julia was proactive and demonstrated leadership qualities."},
    {"apprentice_id": 9, "company_feedback": "Andrew showed excellent teamwork and communication skills."},
    {"apprentice_id": 10, "company_feedback": "Sophie consistently delivered outstanding results and showed great initiative."}
]

In [4]:
# Assuming the schema is already populated as shown above

# Query to find all students with grades > 70% from a specific enrolment date
def find_students_with_good_grades(enrolment_date):
    students_with_good_grades = []
    for enrolment in enrolments:
        if enrolment["enrolment_date"] == enrolment_date:
            enrolment_id = enrolment["enrolment_id"]
            for grade in grades:
                if grade["enrolment_id"] == enrolment_id and grade["grade"] > 70:
                    student_id = enrolment["student_id"]
                    for student in students:
                        if student["student_id"] == student_id:
                            students_with_good_grades.append(student)
                            break
                    break
            break
    return students_with_good_grades

# Example usage
enrolment_date = "2023-01-15"
result_students = find_students_with_good_grades(enrolment_date)
for student in result_students:
    print(student)

{'student_id': 1, 'student_name': 'John Smith', 'student_email': 'john.smith@example.com', 'student_address': '123 Main St, London'}

In [5]:
# Query to display timetable of an apprentice between 2 dates
def display_apprentice_timetable(apprentice_id, start_date, end_date):
    apprentice_timetable = {
        "apprentice_id": apprentice_id,
        "timetable": {
            "academic_commitments": [],
            "work_commitments": []
        }
    }
    # Mock data for academic and work commitments
    # Here we would query actual data from the system based on the apprentice_id and dates
    # For simplicity, using mock data
    apprentice_timetable["timetable"]["academic_commitments"].append({
        "date": "2023-01-20",
        "details": "Attend lecture on Data Structures"
    })
    apprentice_timetable["timetable"]["academic_commitments"].append({
        "date": "2023-01-25",
        "details": "Submit assignment on Algorithms"
    })
    apprentice_timetable["timetable"]["work_commitments"].append({
        "date": "2023-01-21",
        "details": "Work on project A, company ABC"
    })
    apprentice_timetable["timetable"]["work_commitments"].append({
        "date": "2023-01-23",
        "details": "Meeting with team at company XYZ"
    })
    return apprentice_timetable

# Example usage
apprentice_id = 1
start_date = "2023-01-15"
end_date = "2023-02-15"
result_timetable = display_apprentice_timetable(apprentice_id, start_date, end_date)
print(result_timetable)

{'apprentice_id': 1, 'timetable': {'academic_commitments': [{'date': '2023-01-20', 'details': 'Attend lecture on Data Structures'}, {'date': '2023-01-25', 'details': 'Submit assignment on Algorithms'}], 'work_commitments': [{'date': '2023-01-21', 'details': 'Work on project A, company ABC'}, {'date': '2023-01-23', 'details': 'Meeting with team at company XYZ'}]}}

In [7]:
# Calculate average grade for all apprentices for each course
def calculate_average_grade_per_course():
    course_grades = {}
    for enrolment in enrolments:
        course_id = enrolment["course_id"]
        enrolment_id = enrolment["enrolment_id"]
        total_grades = 0
        count_grades = 0
        for grade in grades:
            if grade["enrolment_id"] == enrolment_id:
                total_grades += grade["grade"]
                count_grades += 1
        if count_grades > 0:
            average_grade = total_grades / count_grades
            if course_id in course_grades:
                course_grades[course_id]["average_grade"].append(average_grade)
            else:
                course_grades[course_id] = {
                    "average_grade": [average_grade],
                    "company_grades": {}
                }
    return course_grades

# Calculate average grade by company
def calculate_average_grade_by_company():
    company_grades = {}
    for apprentice in apprentices:
        company_id = apprentice["company_id"]
        if company_id not in company_grades:
            company_grades[company_id] = {
                "average_grade": [],
                "apprentices": []
            }
        company_grades[company_id]["apprentices"].append(apprentice["apprentice_id"])
    for company_id, data in company_grades.items():
        total_grades = 0
        count_grades = 0
        for apprentice_id in data["apprentices"]:
            for feedback_item in feedback:
                if feedback_item["apprentice_id"] == apprentice_id:
                    total_grades += apprentice["final_grade"]
                    count_grades += 1
        if count_grades > 0:
            average_grade = total_grades / count_grades
            data["average_grade"].append(average_grade)
    return company_grades

# Example usage
average_grades_per_course = calculate_average_grade_per_course()
average_grades_by_company = calculate_average_grade_by_company()
print("Average grades per course:", average_grades_per_course)
print("Average grades by company:", average_grades_by_company)

Average grades per course: {101: {'average_grade': [85.0, 80.0, 82.0, 83.0], 'company_grades': {}}, 102: {'average_grade': [78.0, 87.0, 79.0], 'company_grades': {}}, 103: {'average_grade': [92.0, 75.0, 88.0], 'company_grades': {}}}
Average grades by company: {201: {'average_grade': [89.0], 'apprentices': [1, 4, 7, 10]}, 202: {'average_grade': [89.0], 'apprentices': [2, 5, 8]}, 203: {'average_grade': [89.0], 'apprentices': [3, 6, 9]}}

In [8]:
from datetime import datetime, timedelta

# List apprentices who completed their program within the last six months
def list_recently_completed_apprentices():
    today = datetime.today()
    six_months_ago = today - timedelta(days=180)
    recently_completed_apprentices = []
    for apprentice in apprentices:
        completion_date = datetime.strptime(apprentice["completion_date"], "%Y-%m-%d")
        if completion_date >= six_months_ago and completion_date <= today:
            apprentice_details = {
                "apprentice_name": apprentice["apprentice_name"],
                "completion_date": apprentice["completion_date"],
                "final_grade": apprentice["final_grade"]
            }
            for feedback_item in feedback:
                if feedback_item["apprentice_id"] == apprentice["apprentice_id"]:
                    apprentice_details["company_feedback"] = feedback_item["company_feedback"]
                    break
            recently_completed_apprentices.append(apprentice_details)
    return recently_completed_apprentices

# Example usage
recently_completed_apprentices = list_recently_completed_apprentices()
print("Apprentices who completed within last six months:")
for apprentice in recently_completed_apprentices:
    print(apprentice)

Apprentices who completed within last six months: